### ISSUE TITLE
Assignment Deadline confusion

### ISSUE THREAD

**Issue by CharanMN7** [appwrite-octernship/devrel-task-2#2]
Hello, the Assignment deadline in the README.MD is "April 15th" and the deadline in the Octernship tasks website is "May 15th". I'm a little confused with which one of these is the real deadline. Do we have time till May 15th? or is it just up till April 15th? Please update the dates ASAP.

**Comment by tessamero** [comment]
The deadline is April 15th. May 15th is the start of the internship for the selected individuals who best completed the task :) Sorry for the confusion, the process was a bit clunky at the beginning for us to get onboarded, but things got cleared soon after. Please feel free to ask questions on the Discussion board https://github.com/orgs/appwrite-octernship/discussions
